<x-filament-widgets::widget>
<style>
.executive-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem}.executive-card{overflow:hidden;border:1px solid rgba(255,255,255,.08);border-radius:.9rem;background:rgba(24,24,27,.62)}.executive-head{display:flex;justify-content:space-between;border-bottom:1px solid rgba(255,255,255,.08);padding:.85rem 1rem}.executive-title{font-size:.9rem;font-weight:800}.executive-count{border-radius:999px;background:rgba(245,158,11,.14);color:#fbbf24;padding:.2rem .5rem;font-size:.72rem;font-weight:800}.executive-row{display:flex;justify-content:space-between;gap:.75rem;border-bottom:1px solid rgba(255,255,255,.06);padding:.8rem 1rem}.executive-row:last-child{border-bottom:0}.executive-number{font-size:.78rem;font-weight:800}.executive-name{margin-top:.18rem;color:#9ca3af;font-size:.72rem}.executive-date{color:#d1d5db;font-size:.72rem;font-weight:700;text-align:right}.executive-empty{padding:2rem 1rem;color:#9ca3af;font-size:.78rem;text-align:center}@media(max-width:1024px){.executive-grid{grid-template-columns:1fr}}
</style>
<div class="executive-grid">
<section class="executive-card"><header class="executive-head"><span class="executive-title">Próximas retiradas</span><span class="executive-count">{{ $reservations->count() }}</span></header>@forelse($reservations as $reservation)<div class="executive-row"><div><div class="executive-number">{{ $reservation->number }}</div><div class="executive-name">{{ $reservation->customer?->display_name ?? 'Cliente não informado' }}</div></div><div class="executive-date">{{ $reservation->pickup_expected_at?->format('d/m H:i') }}</div></div>@empty<div class="executive-empty">Nenhuma retirada programada.</div>@endforelse</section>
<section class="executive-card"><header class="executive-head"><span class="executive-title">Próximas devoluções</span><span class="executive-count">{{ $returns->count() }}</span></header>@forelse($returns as $return)<div class="executive-row"><div><div class="executive-number">{{ $return->number }}</div><div class="executive-name">{{ $return->contract?->customer?->display_name ?? 'Cliente não informado' }}</div></div><div class="executive-date">{{ $return->scheduled_at?->format('d/m H:i') ?? 'Sem previsão' }}</div></div>@empty<div class="executive-empty">Nenhuma devolução pendente.</div>@endforelse</section>
<section class="executive-card"><header class="executive-head"><span class="executive-title">Próximos vencimentos</span><span class="executive-count">{{ $receivables->count() }}</span></header>@forelse($receivables as $receivable)<div class="executive-row"><div><div class="executive-number">{{ $receivable->number }}</div><div class="executive-name">{{ $receivable->customer?->display_name ?? 'Cliente não informado' }}</div></div><div class="executive-date">{{ $receivable->due_at?->format('d/m/Y') }}<br>R$ {{ number_format((float)$receivable->open_value,2,',','.') }}</div></div>@empty<div class="executive-empty">Nenhum título em aberto.</div>@endforelse</section>
</div>
</x-filament-widgets::widget>
