<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void {
  Schema::create('rental_rate_plans',function(Blueprint $t):void{$t->uuid('id')->primary();$t->foreignUuid('organization_id')->constrained('organizations')->cascadeOnUpdate()->restrictOnDelete();$t->foreignUuid('company_id')->nullable()->constrained('companies')->cascadeOnUpdate()->nullOnDelete();$t->foreignUuid('branch_id')->nullable()->constrained('branches')->cascadeOnUpdate()->nullOnDelete();$t->foreignUuid('asset_category_id')->nullable()->constrained('asset_categories')->cascadeOnUpdate()->nullOnDelete();$t->string('code',50);$t->string('name',150);$t->string('billing_unit',30)->default('daily');$t->decimal('unit_value',15,2)->default(0);$t->decimal('included_distance',15,2)->nullable();$t->decimal('included_hours',15,2)->nullable();$t->decimal('extra_distance_value',15,4)->default(0);$t->decimal('extra_hour_value',15,4)->default(0);$t->decimal('deposit_value',15,2)->default(0);$t->decimal('minimum_value',15,2)->default(0);$t->integer('minimum_quantity')->default(1);$t->integer('priority')->default(100);$t->date('valid_from')->nullable();$t->date('valid_until')->nullable();$t->jsonb('weekdays')->nullable();$t->jsonb('metadata')->nullable();$t->string('status',30)->default('active');$t->timestampsTz();$t->softDeletesTz();$t->unique(['organization_id','code'],'rental_rate_plans_org_code_unique');});
  Schema::create('rental_commercial_items',function(Blueprint $t):void{$t->uuid('id')->primary();$t->foreignUuid('organization_id')->constrained('organizations')->cascadeOnUpdate()->restrictOnDelete();$t->foreignUuid('branch_id')->nullable()->constrained('branches')->cascadeOnUpdate()->nullOnDelete();$t->foreignUuid('asset_category_id')->nullable()->constrained('asset_categories')->cascadeOnUpdate()->nullOnDelete();$t->string('code',50);$t->string('name',150);$t->string('type',30);$t->string('charge_mode',30)->default('per_day');$t->decimal('value',15,2)->default(0);$t->decimal('percentage',8,4)->default(0);$t->decimal('deposit_adjustment',15,2)->default(0);$t->boolean('required')->default(false);$t->boolean('publicly_available')->default(true);$t->date('valid_from')->nullable();$t->date('valid_until')->nullable();$t->jsonb('rules')->nullable();$t->jsonb('metadata')->nullable();$t->string('status',30)->default('active');$t->timestampsTz();$t->softDeletesTz();$t->unique(['organization_id','code'],'rental_commercial_items_org_code_unique');});
  Schema::create('rental_coupons',function(Blueprint $t):void{$t->uuid('id')->primary();$t->foreignUuid('organization_id')->constrained('organizations')->cascadeOnUpdate()->restrictOnDelete();$t->foreignUuid('branch_id')->nullable()->constrained('branches')->cascadeOnUpdate()->nullOnDelete();$t->foreignUuid('asset_category_id')->nullable()->constrained('asset_categories')->cascadeOnUpdate()->nullOnDelete();$t->foreignUuid('business_partner_id')->nullable()->constrained('business_partners')->cascadeOnUpdate()->nullOnDelete();$t->string('code',60);$t->string('name',150);$t->string('discount_type',20)->default('percentage');$t->decimal('discount_value',15,2)->default(0);$t->decimal('maximum_discount_value',15,2)->nullable();$t->decimal('minimum_order_value',15,2)->default(0);$t->integer('usage_limit')->nullable();$t->integer('times_used')->default(0);$t->dateTimeTz('valid_from')->nullable();$t->dateTimeTz('valid_until')->nullable();$t->jsonb('metadata')->nullable();$t->string('status',30)->default('active');$t->timestampsTz();$t->softDeletesTz();$t->unique(['organization_id','code'],'rental_coupons_org_code_unique');});
  Schema::create('rental_commercial_rules',function(Blueprint $t):void{$t->uuid('id')->primary();$t->foreignUuid('organization_id')->constrained('organizations')->cascadeOnUpdate()->restrictOnDelete();$t->foreignUuid('branch_id')->nullable()->constrained('branches')->cascadeOnUpdate()->nullOnDelete();$t->foreignUuid('asset_category_id')->nullable()->constrained('asset_categories')->cascadeOnUpdate()->nullOnDelete();$t->string('code',60);$t->string('name',150);$t->string('rule_type',50);$t->decimal('numeric_value',15,4)->nullable();$t->string('text_value',255)->nullable();$t->boolean('boolean_value')->nullable();$t->jsonb('configuration')->nullable();$t->integer('priority')->default(100);$t->date('valid_from')->nullable();$t->date('valid_until')->nullable();$t->string('status',30)->default('active');$t->timestampsTz();$t->softDeletesTz();$t->unique(['organization_id','code'],'rental_commercial_rules_org_code_unique');});
 }
 public function down():void{Schema::dropIfExists('rental_commercial_rules');Schema::dropIfExists('rental_coupons');Schema::dropIfExists('rental_commercial_items');Schema::dropIfExists('rental_rate_plans');}
};
