<?php
$root=dirname(__DIR__);
function patchFinal(string $file,string $method):void{$c=file_get_contents($file);if(!str_contains($c,$method)){$p=strrpos($c,"\n}");$c=substr_replace($c,$method."\n}",$p,2);file_put_contents($file,$c);}}
patchFinal($root.'/app/Models/Company.php',"\n    public function bankAccounts(): \\Illuminate\\Database\\Eloquent\\Relations\\HasMany { return \$this->hasMany(\\App\\Models\\BankAccount::class); }\n    public function digitalCertificates(): \\Illuminate\\Database\\Eloquent\\Relations\\HasMany { return \$this->hasMany(\\App\\Models\\DigitalCertificate::class); }");
patchFinal($root.'/app/Models/Branch.php',"\n    public function bankAccounts(): \\Illuminate\\Database\\Eloquent\\Relations\\HasMany { return \$this->hasMany(\\App\\Models\\BankAccount::class); }");
patchFinal($root.'/app/Models/BusinessPartner.php',"\n    public function bankAccounts(): \\Illuminate\\Database\\Eloquent\\Relations\\HasMany { return \$this->hasMany(\\App\\Models\\BankAccount::class); }");
$ap=$root.'/app/Models/AccountPayable.php';$c=file_get_contents($ap);$c=str_replace("'metadata'=>'array'","'metadata'=>'array','bank_snapshot'=>'array'",$c);if(!str_contains($c,'function bankAccount()')){$c=str_replace('public function financialAccount(): BelongsTo','public function bankAccount(): BelongsTo { return $this->belongsTo(BankAccount::class); } public function financialAccount(): BelongsTo',$c);}file_put_contents($ap,$c);
$ri=$root.'/app/Models/RentalInvoice.php';$c=file_get_contents($ri);$c=str_replace("'metadata' => 'array',","'metadata' => 'array',\n            'bank_snapshot' => 'array',",$c);if(!str_contains($c,'function bankAccount()')){$c=str_replace('public function contract(): BelongsTo',"public function bankAccount(): BelongsTo\n    {\n        return \$this->belongsTo(BankAccount::class);\n    }\n\n    public function contract(): BelongsTo",$c);}file_put_contents($ri,$c);
$form=$root.'/app/Filament/Resources/AccountPayables/Schemas/AccountPayableForm.php';$c=file_get_contents($form);if(!str_contains($c,"Select::make('bank_account_id')")){$c=str_replace("TextInput::make('document_number')->label('Documento')->maxLength(80),","TextInput::make('document_number')->label('Documento')->maxLength(80), Select::make('bank_account_id')->label('Conta bancária do fornecedor')->relationship('bankAccount','description')->searchable()->preload()->getOptionLabelFromRecordUsing(fn(\$r):string=>\$r->display_name),",$c);}file_put_contents($form,$c);
$controller=$root.'/app/Http/Controllers/Finance/RentalInvoicePdfController.php';$c=file_get_contents($controller);$c=str_replace("'receivables',","'receivables',\n                'bankAccount.bank',",$c);if(!str_contains($c,"'bank' =>")){$c=str_replace("'customer' => \$this->customerData(\$invoice->customer),","'customer' => \$this->customerData(\$invoice->customer),\n            'bank' => \$invoice->bank_snapshot ?: \$invoice->bankAccount?->snapshot(),",$c);}file_put_contents($controller,$c);
$view=$root.'/resources/views/pdf/rental-invoice.blade.php';$c=file_get_contents($view);$r=['LocaÃ§Ã£o'=>'Locação','LOCAÃ‡ÃƒO'=>'LOCAÇÃO','EmissÃ£o'=>'Emissão','CompetÃªncia'=>'Competência','DescriÃ§Ã£o'=>'Descrição','UnitÃ¡rio'=>'Unitário','ObservaÃ§Ãµes'=>'Observações','AcrÃ©scimos'=>'Acréscimos','CondiÃ§Ãµes'=>'Condições','TÃ­tulo'=>'Título','nÃ£o'=>'não','NÃ£o'=>'Não','Ã©'=>'é'];$c=str_replace(array_keys($r),array_values($r),$c);if(!str_contains($c,'DADOS PARA PAGAMENTO')){$block="\n    @if (\$bank)\n        <div class=\"section\"><div class=\"section-title\">DADOS PARA PAGAMENTO</div><table class=\"payment-table\"><tbody><tr><th>Banco</th><td>{{ collect([\$bank['bank_code'] ?? null, \$bank['bank_short_name'] ?? \$bank['bank_name'] ?? null])->filter()->implode(' - ') }}</td><th>Agência</th><td>{{ collect([\$bank['agency'] ?? null, \$bank['agency_digit'] ?? null])->filter()->implode('-') ?: '-' }}</td></tr><tr><th>Conta</th><td>{{ collect([\$bank['account_number'] ?? null, \$bank['account_digit'] ?? null])->filter()->implode('-') ?: '-' }}</td><th>PIX</th><td><strong>{{ \$bank['pix_key'] ?? '-' }}</strong></td></tr></tbody></table></div>\n    @endif\n";$c=str_replace('    @if ($invoice->receivables->isNotEmpty())',$block.'    @if ($invoice->receivables->isNotEmpty())',$c);}file_put_contents($view,$c);
